# -*- coding: utf-8 -*-
"""ETLdadosBovespa2020.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IUkVgmCMefbcYgndF5JH0jfFBwjHxNOy
"""

#ESTE CÓDIGO TEM POR INTUITO FAZER O PROCESSO DE TRANSFORMAÇÃO, EXTRAÇÃO E CARGA (ETL) DE VARIÁVEIS DAS AÇÕES DA BOVESPA DE 2020.
#SAO USADOS COMO EXEMPLO AS VARIÁVEIS DATA DO PREGÃO, CÓDIGO BDI, SIGLA DA AÇÃO, NOME DA AÇÃO, PREÇO DE ABERTURA E FECHAMENTO DA AÇÃO.
#O CÓDIGO EXECUTADO NO COLAB, LÊ OS DADOS (arquivo txt de referência baixado no site da bovespa - COTAHIST_A2020.txt) DO MEU DRIVE DE MESMA CONTA. para 
#MAIS INFORMAÇÕES CONSULTAR PDF LAYOUT DO ARQUIVO – COTAÇÕES HISTÓRICAS

#Importação das bibliotecas necessárias
import pandas as pd #para manipulacao dos data frame
import io 
from google.colab import drive #para importar aquivos do drive para o colab

drive.mount('/content/drive')  #solicitação de permissão para acessar o google drive

position = [(2,10),                 
                (10,12),                  
                (12,24),                  
                (27,39),                  
                (56,69),                                   
                (108,121)                              
              ]                 
                  
    label = ['data_pregao', 'codbdi', 'sigla_acao', 'nome_acao', 'preco_abertura', 'preco_fechamento']                 
    df = pd.read_fwf('/content/drive/My Drive/Colab Notebooks/dados/COTAHIST_A2020.txt', colspecs=position, names=label, skiprows=1)

#filtrar as ações sancionadas pelos regulamentos bmfbovespa (codigo 05) e excluir a coluna do código da ação, pois é tudo 05.
df = df[df['codbdi']==5]
df = df.drop(['codbdi'],1)

#ajusta os campos de data
df['data_pregao'] = pd.to_datetime(df['data_pregao'],format = '%Y%m%d')

# converte de string para float, ou inteiro
df['preco_abertura'] = (df['preco_abertura']/100).astype(float)
df['preco_maximo'] = (df['preco_maximo']/100).astype(float)
df['preco_minimo'] = (df['preco_minimo']/100).astype(float)
df['preco_fechamento'] = (df['preco_fechamento']/100).astype(float)
df['qtd_negocios'] = (df['qtd_negocios']).astype(int)
df['volume_negocios'] = (df['volume_negocios']).astype(int)

#cria arquivo csv, já com os dados transformados. 
df.to_csv('/content/drive/My Drive/Colab Notebooks/dados//historicoBovespa2020.csv', index=False)